In [2]:
import numpy as np
np.__version__


'2.1.3'

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

Code to Convert list to array

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [ ]:
np.arange(10) # 1 argument stop at 10th index

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [12]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [17]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [18]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
np.arange(30,20)

array([], dtype=int64)

In [22]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [24]:
np.arange()# No Parameters

TypeError: arange() requires stop to be specified.

In [25]:
np.arange(10,30,5)# starting from 10 to 30 with step 5 count

array([10, 15, 20, 25])

In [26]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [ ]:
np.zeros(10) # Parameter tuning 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(3,dtype=int) # hyperparameter tuning

array([0, 0, 0])

In [30]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [37]:
zero = np.zeros((2,2))
print(zero)
print('###')
print(type(zero))

[[0. 0.]
 [0. 0.]]
###
<class 'numpy.ndarray'>


In [38]:
print(np.zeros([2,10]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [40]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [43]:
print(np.ones((3,3),dtype=int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [49]:
np.rand(3)

AttributeError: module 'numpy' has no attribute 'rand'

In [ ]:
np.random.rand(3) # 3 random numbers 

array([0.26686781, 0.36437698, 0.81832082])

In [ ]:
np.random.rand(3,5)# np-pkg, random-module and rand-method

array([[0.5894045 , 0.69924385, 0.97756383, 0.70638325, 0.99419445],
       [0.15065872, 0.62743612, 0.14457388, 0.88557077, 0.05214311],
       [0.3493995 , 0.28865675, 0.54538523, 0.04132952, 0.27893798]])

In [ ]:
np.random.randint(4,6)# generate random integer between 4 to 5(6-1)

5

In [ ]:
np.random.randint(2,20,4) # generate 4 randome numbers between 2 to 20 

array([15,  5, 14,  9], dtype=int32)

In [176]:
np.random.randint(30,20,10)

ValueError: low >= high

In [177]:
np.random.randint(-30,20,10)

array([ 18, -14,  12, -20, -19,  17,   6,   0,  -7, -24], dtype=int32)

In [ ]:
np.random.randint(10,30,(10,10))# generate 10-30 with 4*4 matrix

array([[21, 24, 27, 11, 12, 11, 14, 22, 18, 20],
       [10, 23, 18, 21, 10, 27, 22, 27, 29, 10],
       [24, 27, 27, 11, 28, 23, 21, 12, 10, 15],
       [26, 11, 26, 26, 18, 23, 22, 28, 27, 11],
       [17, 11, 11, 28, 10, 20, 16, 26, 26, 13],
       [25, 13, 25, 13, 23, 14, 14, 24, 21, 25],
       [25, 16, 10, 18, 13, 10, 17, 19, 27, 20],
       [28, 10, 13, 20, 15, 29, 14, 19, 27, 15],
       [14, 16, 27, 10, 10, 26, 11, 21, 29, 11],
       [15, 11, 27, 15, 23, 10, 14, 10, 22, 14]], dtype=int32)

In [182]:
np.random.randint(1,100,(12,12))

array([[67, 87, 77, 18, 37, 46,  9,  9,  4, 85,  3, 48],
       [47, 18, 81, 12, 75, 61, 61, 31, 24, 95, 87, 39],
       [79, 17, 85, 25, 93, 13,  2, 85, 13, 16, 27,  6],
       [ 9, 14, 31, 38, 40, 47, 56, 27, 64, 40, 65, 71],
       [38, 29, 58, 12, 31, 64, 24,  5, 42, 98, 52, 78],
       [12, 24,  6, 71,  3, 62, 58,  6, 37, 59, 89, 49],
       [43, 53, 69, 95, 57, 19, 49, 61, 25, 94, 74,  8],
       [27, 98,  9, 80, 82, 75, 41, 45, 77, 21, 67, 48],
       [33,  8, 10, 73, 21, 44, 15,  4,  2,  2, 12, 87],
       [14, 57, 44, 70,  6, 43, 68, 81, 94, 46, 40, 28],
       [53, 20, 92, 72,  9, 90, 35, 57,  4, 34, 29, 41],
       [50, 90, 77, 80, 62, 41, 23, 67, 90, 48,  7, 28]], dtype=int32)

In [183]:
arr

array([0, 1, 2, 3, 4, 5])

In [195]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [196]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [197]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [198]:
np.arange(1,13).reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [221]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

SLICING in MATRIX

In [223]:
b=np.random.randint(10,20,(5,4))# 5 into 4 matrix with 10,20 values
print(b)

[[10 12 13 18]
 [17 14 10 15]
 [16 15 17 13]
 [12 19 17 16]
 [11 18 11 11]]


In [224]:
b[:]

array([[10, 12, 13, 18],
       [17, 14, 10, 15],
       [16, 15, 17, 13],
       [12, 19, 17, 16],
       [11, 18, 11, 11]], dtype=int32)

In [225]:
type(b)

numpy.ndarray

In [ ]:
b[0] # first row

array([10, 12, 13, 18], dtype=int32)

In [ ]:
b[4] # last row

array([11, 18, 11, 11], dtype=int32)

In [228]:
b[-4]

array([17, 14, 10, 15], dtype=int32)

In [231]:
b[1]

array([17, 14, 10, 15], dtype=int32)

In [232]:
print(b)

[[10 12 13 18]
 [17 14 10 15]
 [16 15 17 13]
 [12 19 17 16]
 [11 18 11 11]]


In [ ]:

print(b[1:3])# get 2nd and 3rd row from array

[[17 14 10 15]
 [16 15 17 13]]


In [ ]:
print(b[1,3]) # this means 1st row and 3rd column

15


In [236]:
b[2:3]

array([[16, 15, 17, 13]], dtype=int32)

In [200]:
arr[::-2]
arr

array([0, 1, 2, 3, 4, 5])

In [237]:
arr[::-3]

array([5, 2])

In [242]:
arr=np.random.randint(0,100,(10,10))
arr

array([[54, 32, 95, 28, 59, 61, 77, 69, 34, 18],
       [ 0, 54, 66, 55, 71,  3, 45, 71, 51, 99],
       [15, 96, 46, 12,  4, 77, 88, 15, 38, 91],
       [ 0, 65, 89, 69, 97, 88, 81, 52, 26, 88],
       [11, 42, 63,  7, 55, 93, 66, 41, 27, 61],
       [80, 39, 92, 70, 67, 29,  3,  1, 43, 29],
       [57, 24, 35, 76, 13,  0, 95, 35, 54, 69],
       [86, 55, 23, 12, 78, 85, 38, 68, 38, 41],
       [78, 32, 12, 41, 92, 90, 10, 84,  2, 41],
       [86, 94, 70, 26,  3, 51, 37, 18, 73, 88]], dtype=int32)

In [243]:
arr[0:10:3]

array([[54, 32, 95, 28, 59, 61, 77, 69, 34, 18],
       [ 0, 65, 89, 69, 97, 88, 81, 52, 26, 88],
       [57, 24, 35, 76, 13,  0, 95, 35, 54, 69],
       [86, 94, 70, 26,  3, 51, 37, 18, 73, 88]], dtype=int32)

In [245]:
print(arr.max())

99


In [246]:
arr.mean()

np.float64(51.08)

In [ ]:
median(arr)

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
from numpy import * # import all numpy function  
median(([1,2,3,4,5]))

np.float64(3.0)

INDEXING

In [258]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [260]:
mat = np.arange(0,100).reshape(10,10)
row=4
col=5
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [259]:
mat[row,col]
print(mat[row,col])

46


In [ ]:
col=6
print(mat[:,col]) # print only column
print(type(mat[:,6]))

[ 6 16 26 36 46 56 66 76 86 96]
<class 'numpy.ndarray'>


In [209]:
mat[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [269]:
mat[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
mat[:,3] 

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [212]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [214]:
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [270]:
print(type(mat[2,2]))

<class 'numpy.int64'>


In [ ]:
mat[2:6,2:4] # 2:6 row and 2:4 is column part

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [273]:
mat[2:3,2:3]

array([[22]])

Numpy Masking