## Array Creation Functions

In [1]:
import numpy as np

In [2]:
# Create an array from list
arr=np.array([1,2,3,4])
print("Array arr: ",arr)

Array arr:  [1 2 3 4]


In [4]:
# Create an array with evenly spaced value (all even values)
evenarray = np.arange(0,22,2)
print("Array evenarray: ",evenarray)

Array evenarray:  [ 0  2  4  6  8 10 12 14 16 18 20]


In [10]:
# create an array filled with zeros
d= np.zeros((3,2),dtype=int)
print(d)

[[0 0]
 [0 0]
 [0 0]]


In [11]:
# create an array filled with 1s
d= np.ones((3,2),dtype=int)
print(d)

[[1 1]
 [1 1]
 [1 1]]


In [14]:
#Create an identity matrix
f=np.eye(4,dtype=int) # 4*4 identity matrix
print("Identity matrix f: \n",f)

Identity matrix f: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


##  Array Manipulation Functions

In [20]:
#Reshape an array
a1=np.array([1,2,3,2,1,0])
reshaped=np.reshape(a1,(2,3)) # Reshape to 1*5
print("Reshaped array: \n",reshaped)

Reshaped array: 
 [[1 2 3]
 [2 1 0]]


In [ ]:
# Flatten an array - create linear vector
f1=np.array([[1,2],[3,4],[5,6],[7,8]])
print(f1)
flattened=np.ravel(f1)
print("Flattened Array: \n",flattened)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Flattened Array: 
 [1 2 3 4 5 6 7 8]


In [25]:
# Transpose an array
e1=np.array([[1,2],[3,4]])
print("Original Array :\n",e1)
transposed = np.transpose(e1)
print("Transposed array:\n",transposed)

Original Array :
 [[1 2]
 [3 4]]
Transposed array:
 [[1 3]
 [2 4]]


In [26]:
# Stack Arrays Vertically
a2= np.array([1,2])
b2= np.array([3,4])
stacked = np.vstack([a2,b2]) # stack a and b vertically
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


## Mathematical Functions

In [ ]:
g=np.array([1,2,3,4])
added = np.add(g,2) # Add 2 to each element
print(added)

[3 4 5 6]


In [ ]:
np.power(g,2) # Square to each element

array([ 1,  4,  9, 16])

In [30]:
np.sqrt(g) # sq root for each

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [34]:
print(a1)
print(a1)

[1 2 3 2 1 0]
[1 2 3 2 1 0]


In [36]:
#Dot product of two arrays
a2=np.array([1,2,3])
dot_product = np.dot(a2,a2)
print("Dot product of a and g:",dot_product)

Dot product of a and g: 14


## Statistical Function

In [37]:
s=np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s: ",mean)

Mean of s:  2.5


In [38]:
std_dev = np.std(s)
print("Std Deviation of s: ",std_dev)

Std Deviation of s:  1.118033988749895


In [39]:
minimum = np.min(s)
print("Minimum of s: ",minimum)

Minimum of s:  1


In [40]:
mx = np.max(s)
print("Maximum of s: ",mx)

Maximum of s:  4


## Linear Algebra Functions

In [42]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

## Random Sampling functions

In [ ]:
rnp.random.rand(3)

array([0.05347799, 0.90713267, 0.8838029 ])

In [63]:
rand_ints = np.random.randint(0,10,size=5)
print(rand_ints)

[3 0 3 5 0]


In [67]:
# Set seed for reproducibility -- FIXED VALUES with RANDOM FUNCTION
np.random.seed(0)

# Now Generate random integers
rand_ints = np.random.randint(0,10,size=5)
print(rand_ints)


[5 0 3 3 7]


## Boolean and Logical Function

In [69]:
#check if all elements are True
logical_test = np.array([True, False,True])
all_true = np.all(logical_test)
print("Is all elements True : ",all_true)

Is all elements True :  False


## Set Operations

In [71]:
# Intersection of 2 arrays 
s=np.array([1,2,3,4])
s1=np.array([3,2,39,40])
intersection = np.intersect1d(s,s1)
print("Intersection of s and s1 :", intersection)

Intersection of s and s1 : [2 3]


In [72]:
# Intersection of 2 arrays 
s=np.array([1,2,3,4])
s1=np.array([3,2,39,40])
union = np.union1d(s,s1)
print("Union of s and s1 :", union)

Union of s and s1 : [ 1  2  3  4 39 40]


## Array Attribute Functions

In [75]:
shape = s1.shape
print(shape)

(4,)


In [76]:
s1.size

4

In [77]:
s1.ndim

1

In [78]:
s1.dtype

dtype('int64')

## Other functions

In [79]:
s1.nbytes

32

In [80]:
np.shares_memory(s1,np.copy(s1))

False